# Generated by Django 3.0.8 on 2020-07-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gc_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='easternwebaccount',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='easternwebaccount',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='easternwebaccount',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='easternwebaccount',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
